### ISSUE TITLE
播放速度不流畅

### ISSUE THREAD

**Issue by imzf** [m13253/BiliDan#11]
如题，使用 BiliDan 播放某些视频时经常会出现卡滞的情况，而在网站观看时则不会
系统：ubuntu 14.04
带宽：8mb
卡滞视频网址：http://www.bilibili.com/video/av1515377/

**Comment by saiatsai** [comment]
这个很卡
bilidan --mpvflags ' --cache=1048576 ' http://www.bilibili.com/video/av2111834/
直接换成mpv http://www.bilibili.com/video/av2111834/来播放就很流畅
是什么问题？

mpv版本
mpv 0.8.3 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-03-17T07:32:24
ffmpeg library versions:
   libavutil       54.20.100
   libavcodec      56.26.100
   libavformat     56.25.101
   libswscale      3.1.101
   libavfilter     5.11.102
   libswresample   1.1.100

**Comment by saiatsai** [comment]
bilidan -v --mpvflags ' --cache=1048576 ' http://www.bilibili.com/video/av2111834/


DEBUG: Detected mpv version: 0.8.3
INFO: Loading video info...
DEBUG: Fetch: http://api.bilibili.com/view?id=2111834&sign=747e89df0ac0fb33ba16ead64d42254e&type=json&page=1&appkey=85eb6835b0a1034e
INFO: Got video cid: 3277082
INFO: Loading video content...
DEBUG: Fetch: http://interface.bilibili.com/playurl?cid=3277082&appkey=85eb6835b0a1034e&sign=0ef62198c64850fe99e4f11ba0396266
INFO: Got media URLs:
      1: http://zj-cm10.acgvideo.com/7/63/3277082-1.flv?expires=1426778700&ssig=Qf-1zdNY1xI31tiv6bDL9g&o=3746125519&rate=64000
INFO: Determining video resolution...
DEBUG: Executing: ffprobe -icy 0 -loglevel repeat+warning -print_format json -select_streams v -show_streams -timeout 60000000 -user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36' -- 'http://zj-cm10.acgvideo.com/7/63/3277082-1.flv?expires=1426778700&ssig=Qf-1zdNY1xI31tiv6bDL9g&o=3746125519&rate=64000'
INFO: Video resolution: 1280x720
INFO: Loading comments...
DEBUG: Fetch: http://comment.bilibili.com/3277082.xml
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-g7a3w_t2.ass
WARNING: Invalid comment: <d p="335.29998779297,1,25,16777215,1426406867,0,D1259659,836269963"/>
WARNING: Invalid comment: <d p="906.47399902344,1,25,16777215,1426488099,0,Deedd32b,837320808"/>
INFO: Launching media player...
DEBUG: Compare mpv version: 0.8.3 >= 0.6
DEBUG: Compare mpv version: 0.8.3 >= 0.4
DEBUG: Executing: mpv --autofit 950x540 --cache-file TMP --framedrop vo --http-header-fields 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML\, like Gecko) Chrome/36.0.1985.125 Safari/537.36' --media-title '纯黑《教团1886》第五期 最高难度全收集攻略解说' --no-video-aspect --sub-ass --sub-file /tmp/tmp-danmaku2ass-g7a3w_t2.ass --vf 'lavfi="fps=fps=60:round=down"' --cache=1048576 -- 'http://zj-cm10.acgvideo.com/7/63/3277082-1.flv?expires=1426778700&ssig=Qf-1zdNY1xI31tiv6bDL9g&o=3746125519&rate=64000'
Playing: http://zj-cm10.acgvideo.com/7/63/3277082-1.flv?expires=1426778700&ssig=Qf-1zdNY1xI31tiv6bDL9g&o=3746125519&rate=64000
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
 (+) Subs  --sid=1 'tmp-danmaku2ass-g7a3w_t2.ass' (ass) (external)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
fontconfig: cannot find glyph U+0E51 in font 'SimHei', falling back to 'Arial Unicode MS'
AV: 00:00:13 / 00:43:44 (0%) A-V:  0.000 Dropped: 12 Cache:  2s+682KB
fontconfig: cannot find glyph U+1D98 in font 'SimHei', falling back to 'Unifont'
AV: 00:00:18 / 00:43:44 (0%) A-V: -0.000 Dropped: 14 Cache:  1s+6KB
[cache] Cache is not responding - slow/stuck network connection?
AV: 00:00:20 / 00:43:44 (0%) A-V:  0.000 Dropped: 17 Cache:  0s+0KB
[cache] Cache is not responding - slow/stuck network connection?
(Buffering) AV: 00:00:21 / 00:43:44 (0%) A-V:  0.000 Dropped: 18 Cache:  1s+2KB
[cache] Cache keeps not responding.
(Buffering) AV: 00:00:24 / 00:43:44 (0%) A-V:  0.000 Dropped: 18 Cache:  0s+2KB
[cache] Cache keeps not responding.
AV: 00:00:25 / 00:43:44 (0%) A-V:  0.000 Dropped: 18 Cache:  1s+2KB
[cache] Cache is not responding - slow/stuck network connection?
(Buffering) AV: 00:00:27 / 00:43:44 (1%) A-V:  0.000 Dropped: 18 Cache:  1s+2KB
[cache] Cache is not responding - slow/stuck network connection?
AV: 00:00:29 / 00:43:44 (1%) A-V: -0.000 Dropped: 18 Cache:  0s+22KB
[cache] Cache keeps not responding.
(Buffering) AV: 00:00:30 / 00:43:44 (1%) A-V:  0.000 Dropped: 18 Cache:  1s+2KB
[cache] Cache keeps not responding.
AV: 00:00:33 / 00:43:44 (1%) A-V: -0.000 Dropped: 20 Cache:  0s+3KB
[cache] Cache is not responding - slow/stuck network connection?
(Buffering) AV: 00:00:33 / 00:43:44 (1%) A-V: -0.000 Dropped: 20 Cache:  0s+3KB

**Comment by m13253** [comment]
建议暂停去喝(chōu)口(gēn)水(yān)，回来也许就不卡了。
或者试试 --source html5 的低画质版？
