### ISSUE TITLE
乐视某些视频源只解析到广告

### ISSUE THREAD

**Issue by amazingfate** [m13253/BiliDan#18]
比如: http://www.bilibili.com/video/av1792430/

**Comment by m13253** [comment]
新增了硕鼠视频解析。
使用 `--source flvcd` 来启动它。
应该能解决这个问题吧。

**Comment by cnbeining** [comment]
1. 考虑使用FLVCD。

2. 爱奇艺无效。缺八辈子德的网站。。

Beining

**Comment by m13253** [comment]
> 1. 考虑使用FLVCD。

我不是已经说了硕鼠解析乐视版权番失败了么……

**Comment by cnbeining** [comment]
写错了，FLVXZ。。。。

顺便，硕鼠可以通过拆播放器的办法 偷链接。

但是真恶心人。。。

Beining

**Comment by m13253** [comment]
> 写错了，FLVXZ。。。。

我试了一下 FLVXZ，解析进度条滚了几分钟了还没有结果。

> 顺便，硕鼠可以通过拆播放器的办法 偷链接。

详细说说？

**Comment by lixiaoyan** [comment]
flash 播放器里的解析逻辑似乎可以反编译出来的.
文件: `org.lala.utils.PlayerTool`.

**Comment by lixiaoyan** [comment]
具体没仔细研究, 不过代码里面的确用到了 flascc, 部分工具可以反编译出来一些代码似乎, 不过基本没法看.

**Comment by cnbeining** [comment]
@lixiaoyan 

混淆了。(╯‵□′)╯︵┻━┻

@m13253 

抓包他的客户端，diy-****** ，检查其到服务器连接，里面有真实地址。

**Comment by lixiaoyan** [comment]
@cnbeining flascc 本身就跟混淆效果差不多, 毕竟 llvm -> avm 这种转换本身就是黑科技了.

**Comment by cnbeining** [comment]
用Pr模式应该可破。

🌰：

```<video>
<result>succ</result>
<timelength>1350149</timelength>
<src>30</src>
<durl>
<order>0</order>
<length>1350149</length>
<url>
<![CDATA[
http://g3.letv.cn/vod/v2/MTEwLzQyLzUwL2xldHYtdXRzLzE0L3Zlcl8wMF8yMC0zMDAxMjk3NjItYXZjLTE1NDI1NTQtYWFjLTEyODAwMS0xMzUwMTQ5LTI4NDE2MjcwOS0yMTg4NThjY2ZmOGFlMmM2MDc0MzI5ZGViOGJiMDBlYS0xNDE4MzE0MTY5MTQ4Lm1wNA==?b=1682&mmsid=25305121&tm=1425461546&key=0b7e1ab11768dcac10ab185675dcfad4&platid=2&splatid=201&playid=0&tss=no&vtype=52&cvid=302673371813&pip=908cfe744c62db8e37a9f5454672bbc3&termid=1&bcloud=S7&sign=bcloud_100172&format=0&tag=flash&ostype=windows&hwtype=un&retry=1
]]>
</url>
</durl>
</video>```

**Comment by m13253** [comment]
> 用Pr模式应该可破。

pr 模式我早加上了。
用 `--source bilipr` 启动。

**Comment by cnbeining** [comment]
在Biligrab测试，使用BilibiliPr模式可以正常下载弹幕，下载视频，转换ASS并播放。

可以考虑关闭此issue，待问题复现时重新开启。

Beining

**Comment by m13253** [comment]
感谢 Beining 的帮助。回 issue好快！

关闭。
