### ISSUE TITLE
有些视频某段卡顿

### ISSUE THREAD

**Issue by kosmosR2** [m13253/BiliDan#23]
比如http://www.bilibili.com/video/av2033512/
大概50秒开始到58秒结束。关掉弹幕的话就好了。
应该是解析弹幕卡？没看过bilidan源码不清楚。。。
是这样的话不知道什么时候会被刷掉。再遇到我再贴。
截图的话感觉没意义啊。。。

*bilidan为当前最新*
bilidan --cookie "..." --mpvflags ' --cache=1048576 '  http://www.bilibili.com/video/av2033512/
*MPV版本*
mpv 0.8.0 (C) 2000-2015 mpv/MPlayer/mplayer2 projects
 built on 2015-02-23T17:57:54
ffmpeg library versions:
   libavutil       54.15.100
   libavcodec      56.13.100
   libavformat     56.15.102
   libswscale      3.1.101
   libavfilter     5.2.103
   libswresample   1.1.100

**Comment by m13253** [comment]
我这里没有任何卡。
难道是我的硬件太好了？
3小时应该不会把弹幕刷走的吧？

**Comment by kosmosR2** [comment]
晕，我早上起来那段也不卡了。。。

这次来个冷门的
bilidan --cookie "..." --mpvflags ' --cache=1048576 ' http://www.bilibili.com/video/av1873101/
6：17开始

要是你还不卡我就考虑换电脑了。。。

**Comment by m13253** [comment]
我录了一段 https://www.youtube.com/watch?v=RM_5gCE1zVk
录制 FPS 是 25。
目测没有卡。
你调教调教 MPV 的 `--hwdec` `--framedrop` 等参数试试？（用 `--mpvflags=""` 来喂）

**Comment by kosmosR2** [comment]
http://youtu.be/n7gT1iUETrU 

我们世界线不一样？。。。

**Comment by m13253** [comment]
看了你的录像我终于明白了。
网速不够，Cache 跑光了，暂停一会再播就可以了。
至于为什么一关弹幕就不卡了，这和“发弹幕求不卡”是一样的玄学道理。

**Comment by kosmosR2** [comment]
玄学。。。

**Comment by m13253** [comment]
网速不好的话，可以用 --source html5 来获取低画质视频（优酷、腾讯、版权番除外）
