### ISSUE TITLE
Can not open external file /tmp/tmp-danmaku2ass-46vcnms6.ass.

### ISSUE THREAD

**Issue by skt041959** [m13253/BiliDan#24]
播放av314的时候，没有弹幕

$  ./bilidan.py http://www.bilibili.com/video/av314/ 

INFO: Loading video info...
INFO: Got video cid: 529622
INFO: Loading video content...
INFO: Got media URLs:
      1: http://edge.v.iask.com.lxdns.com/83873314.hlv?KID=sina,viask&Expires=1424966400&ssig=HA5drDRw6H
INFO: Determining video resolution...
INFO: Video resolution: 512x384
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-46vcnms6.ass
ERROR: '8'
ERROR: Danmaku2ASS failed, comments are disabled.
INFO: Launching media player...
Playing: http://edge.v.iask.com.lxdns.com/83873314.hlv?KID=sina,viask&Expires=1424966400&ssig=HA5drDRw6H
[ytdl_hook] youtube-dl not found, not executable, or broken.
Can not open external file /tmp/tmp-danmaku2ass-46vcnms6.ass.
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [pulse] 44100Hz stereo 2ch float
VO: [opengl] 512x384 yuv420p
AV: 00:01:35 / 00:01:36 (99%) A-V:  0.000 Dropped: 6 Cache:  0s+0KB

我去/tmp/tmp-danmaku2ass-46vcnms6.ass 看了一下，长度为0

**Comment by m13253** [comment]
我播放成功了。
请问：
1. 你的 Danmaku2ASS 模块版本是否为最新？（删了 `danmaku2ass.py` 再启动会自动更新）
2. 你的 Python3 版本是多少？（启动 `python3` 第一行有提示）
3. 其它视频可以播放吗？

**Comment by skt041959** [comment]
1. Danmaku2ASS是最新的
2. Python3.4
3. 给出的4个视频，其他三个都可以

**Comment by m13253** [comment]
请加上 -d -v 两个参数，它会提供更多有价值的信息。
谢了。

**Comment by skt041959** [comment]
$ ./bilidan.py -d -v http://www.bilibili.com/video/av314/

DEBUG: Detected mpv version: 0.8.0
INFO: Loading video info...
DEBUG: Fetch: http://api.bilibili.com/view?appkey=85eb6835b0a1034e&page=1&type=json&id=314&sign=babbb44b2d7e41743b016ac7d8221b62
INFO: Got video cid: 529622
INFO: Loading video content...
DEBUG: Fetch: http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&sign=d5bd30833fb98756df789c2ff2d0da7c&cid=529622
INFO: Got media URLs:
      1: http://edge.v.iask.com.lxdns.com/83873314.hlv?KID=sina,viask&Expires=1424966400&ssig=HA5drDRw6H
INFO: Determining video resolution...
DEBUG: Executing: ffprobe -icy 0 -loglevel repeat+warning -print_format json -select_streams v -show_streams -timeout 60000000 -user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36' -- 'http://edge.v.iask.com.lxdns.com/83873314.hlv?KID=sina,viask&Expires=1424966400&ssig=HA5drDRw6H'
INFO: Video resolution: 512x384
INFO: Loading comments...
DEBUG: Fetch: http://comment.bilibili.com/529622.xml
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-6utyyuny.ass
ERROR: '8'
Traceback (most recent call last):
  File "./bilidan.py", line 466, in <module>
    sys.exit(main())
  File "./bilidan.py", line 451, in main
    retval = retval or biligrab(url, debug=args.debug, verbose=args.verbose, media=args.media, cookie=args.cookie, quality=quality, source=source, mpvflags=mpvflags, d2aflags=d2aflags)
  File "./bilidan.py", line 296, in biligrab
    comment_out = convert_comments(video_metadata['cid'], video_size)
  File "./bilidan.py", line 207, in convert_comments
    log_or_raise(e, debug=debug)
  File "./bilidan.py", line 406, in log_or_raise
    raise exception
  File "./bilidan.py", line 205, in convert_comments
    danmaku2ass.Danmaku2ASS([comment_in], comment_out, **d2a_args)
  File "/home/skt/code/BiliDan/danmaku2ass.py", line 777, in Danmaku2ASS
    comments = ReadComments(input_files, font_size)
  File "/home/skt/code/BiliDan/danmaku2ass.py", line 805, in ReadComments
    comments.extend(CommentProcessor(FilterBadChars(f), font_size))
  File "/home/skt/code/BiliDan/danmaku2ass.py", line 181, in ReadCommentsBilibili
    yield (float(p[0]), int(p[4]), i, c, {'1': 0, '4': 2, '5': 1, '6': 3}[p[1]], int(p[3]), size, (c.count('\n')+1)*size, CalculateLength(c)*size)
KeyError: '8'

**Comment by m13253** [comment]
这是修 https://github.com/m13253/danmaku2ass/issues/16 的时候的副作用。
正在抢修中。

**Comment by m13253** [comment]
已修复。请删除现有的 danmaku2ass.py 文件。
下次启动的时候会自动更新。
如果有问题请再告诉我。
