### ISSUE TITLE
会员的世界有办法播放吗0 0

### ISSUE THREAD

**Issue by byljcron** [m13253/BiliDan#25]
rt，，
bilidan -v  -d http://www.bilibili.com/video/av2095086/                                                                            
DEBUG: Detected mpv version: 0.8.2
INFO: Loading video info...
DEBUG: Fetch: http://api.bilibili.com/view?id=2095086&type=json&page=1&appkey=85eb6835b0a1034e&sign=a8d38ffbca26176a0e8187b435ed2f5d
ERROR: Error message: no perm error, please login.
ERROR: Can not get 'cid' from http://www.bilibili.com/video/av2095086/
Traceback (most recent call last):
  File "/usr/share/bilidan/bilidan.py", line 466, in <module>
    sys.exit(main())
  File "/usr/share/bilidan/bilidan.py", line 451, in main
    retval = retval or biligrab(url, debug=args.debug, verbose=args.verbose, media=args.media, cookie=args.cookie, quality=quality, source=source, mpvflags=mpvflags, d2aflags=d2aflags)
  File "/usr/share/bilidan/bilidan.py", line 276, in biligrab
    video_metadata = fetch_video_metadata(aid, pid)
  File "/usr/share/bilidan/bilidan.py", line 99, in fetch_video_metadata
    raise ValueError('Can not get \'cid\' from %s' % url)
ValueError: Can not get 'cid' from http://www.bilibili.com/video/av2095086/
                                                                                  
会员的世界会返回一个未登录error orz2333
我试了下把登录过的cookie导入依然访问不能orz

**Comment by cnbeining** [comment]
无法复现。

你的使用方法正确么？使用的cookie是最新的么？IP一致么？脸黑么？

附：LOG

```
Beining$ python3 bilidan.py  -v -d http://www.bilibili.com/video/av2095086/ -c '_cnt_dyn=0;_cnt_notify=0;_cnt_pm=0;DedeID=WTF;DedeUserID=poi;DedeUserID__ckMd5=poi;pgv_pvi=poi;SESSDATA=poi;sid=poi;__track_isp_speed=1;CNZZDATApoi=poi;'
ERROR: Automatically downloading 'danmaku2ass.py'
       from https://github.com/m13253/danmaku2ass
       to /Users/Beining/Movies/BiliDan/danmaku2ass.py
DEBUG: Fetch: https://github.com/m13253/danmaku2ass/raw/master/danmaku2ass.py
DEBUG: Detected mpv version: 0.3.5-git-76d771a
INFO: Loading video info...
DEBUG: Fetch: http://api.bilibili.com/view?appkey=85eb6835b0a1034e&id=2095086&sign=a8d38ffbca26176a0e8187b435ed2f5d&type=json&page=1
INFO: Got video cid: 3248535
INFO: Loading video content...
DEBUG: Fetch: http://interface.bilibili.com/playurl?appkey=85eb6835b0a1034e&sign=b68204e287e0ab552aabe0175cbfcd6f&cid=3248535
INFO: Got media URLs:
      1: http://ws.acgvideo.com/4/11/3248535-1.flv
INFO: Determining video resolution...
DEBUG: Executing: ffprobe -icy 0 -loglevel repeat+warning -print_format json -select_streams v -show_streams -timeout 60000000 -user-agent 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36' -- http://ws.acgvideo.com/4/11/3248535-1.flv
^Z
[1]+  Stopped
```

**Comment by m13253** [comment]
> 你的使用方法正确么？使用的cookie是最新的么？IP一致么？脸黑么？

cn北宁君所言极是。
~~大概是脸黑~~

**Comment by m13253** [comment]
另外经过测试，bilibili 实际检查的 Cookie 字段是 DedeUserID DedeUserID__ckMd5 SESSDATA 三个。
还有试试浏览器里登出再登录，再取 Cookie。

**Comment by cnbeining** [comment]
@m13253 +1. 这么写只是为了导出方便。

另，检查格式是不是和我的一致。

又及，偶尔会出现```SESSDATA```已经过期却可以正常登陆的现象。特别是多浏览器，多IP的时候。

试着进一下个人空间修改投稿吧。

**Comment by byljcron** [comment]
重新登录后再取出就正常了
多谢ww
