### ISSUE TITLE
There is no sound

### ISSUE THREAD

**Issue by Yutousama** [m13253/BiliDan#26]
没有声音。。。。。

**Comment by cnbeining** [comment]
请：

- 保证使用了最新版脚本
- 保证使用了最新版软件
- 保证系统解码器以及依赖关系良好
- 确定问题可以复现
- 确定不是因为个人设置问题，或者默认设置问题（软/硬件）

请准备好日志以及测试视频，删除其中可能涉及的敏感信息，在这里提出。

对您造成的不便，表示歉意。

**Comment by m13253** [comment]
建议同楼上。

日志请用 -vd 参数获得。

另尝试一下 --mpvflags="--ao=alsa"

**Comment by m13253** [comment]
Duplicate #16, closing
