### ISSUE TITLE
代码好像没有通过pep8

### ISSUE THREAD

**Issue by tywtyw2002** [m13253/BiliDan#29]
rt

为了增加可读性，最好符合下pep8。

**Comment by cnbeining** [comment]
不要为了pep8而pep8。（喂

可以用autopep8嘛。但是我不会完全遵守的。。。

tywtyw2002 <notifications@github.com>于2015年4月5日星期日写道：

**Comment by m13253** [comment]
代码通过了除每行78字符限制之外的所有 PEP8 检查。
