### ISSUE TITLE
木有视频,弹幕输出在终端里面,有声音.

### ISSUE THREAD

**Issue by kexul** [m13253/BiliDan#30]
终端输出如下:
kkk@kkk-ThinkPad-Edge-E530:~$ ./bilidan.py http://www.bilibili.com/video/av2273687/
INFO: Loading video info...
INFO: Got video cid: 3544591
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-hnhy1-dx.acgvideo.com/vg4/c/0b/3544591-1.flv?expires=1430567700&ssig=or59IGSY4pUtPMGs-9wWgg&o=1873787758&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 1280x720
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-dyybhzh7.ass
WARNING: Invalid comment: <d p="9.3909997940063,5,25,15138834,1430412739,0,21cfb198,883431766"/>
WARNING: Invalid comment: <d p="90.28099822998,1,25,16777215,1430440299,0,8843468e,883655220"/>
INFO: Launching media player...
Playing: http://cn-hnhy1-dx.acgvideo.com/vg4/c/0b/3544591-1.flv?expires=1430567700&ssig=or59IGSY4pUtPMGs-9wWgg&o=1873787758&rate=0
[ytdl_hook] Traceback (most recent call last):
[ytdl_hook]   File "/usr/bin/youtube-dl", line 3, in <module>
[ytdl_hook]     import youtube_dl
[ytdl_hook] ImportError: No module named 'youtube_dl'
[ytdl_hook] Your version of youtube-dl is too old! You need at least version '2014.11.26', try running `youtube-dl -U`. 
[libav/demuxer] flv: max_analyze_duration 5000000 reached
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
 (+) Subs  --sid=1 'tmp-danmaku2ass-dyybhzh7.ass' (ass) (external)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [pulse] 44100Hz stereo 2ch float
[libav] fps: No such option: round.
[libav] AVFilterGraph: Error initializing filter 'fps' with args 'fps=60:round=down'
[lavfi] Can't configure libavfilter graph.
Video filter chain:
 [vd] 1280x720 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264
 [in] 1280x720 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264
 [lavfi] 1280x720 yuv420p BT.709 (HD)/TV CL=mpeg2/4/h264   <---
 [out] ???
Cannot initialize video filters.
Could not initialize video chain.
Video: no video

**Comment by m13253** [comment]
你的发行版应该是旧版 Debian 或者 Ubuntu 吧？
我在最新版 BiliDan (8c9b73372a8a6ad4510dc0287e2ef20dc4658001) 加入了 `--keep-fps` 选项。
用这个选项启动试试。
(Duplicate #22)

**Comment by kexul** [comment]
谢了,加入 --keep-fps确实解决了问题,不过我的发行版是ubuntu15.04哟~

**Comment by lianxiangru** [comment]
同15.04，出现了同样的问题

**Comment by m13253** [comment]
> 同15.04，出现了同样的问题

用参数 `--keep-fps`。
