### ISSUE TITLE
播放视频只在终端输出弹幕，不弹出播放器

### ISSUE THREAD

**Issue by Vector2001** [m13253/BiliDan#31]
heracles@Avenger:~$ ./bilidan.py http://www.bilibili.com/video/av314
INFO: Loading video info...
INFO: Got video cid: 3262388
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-hbjm1-dx.acgvideo.com/vg1/5/ae/3262388-1.flv?expires=1430664900&ssig=mLl9HMRnE9FxLEPkTDHQqQ&o=2874353341&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 512x384
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-hkjcs6xz.ass
WARNING: Invalid comment: '/n/n/n/n ~~BILIBILI'
WARNING: Invalid comment: '- -'
INFO: Launching media player...
Playing: http://cn-hbjm1-dx.acgvideo.com/vg1/5/ae/3262388-1.flv?expires=1430664900&ssig=mLl9HMRnE9FxLEPkTDHQqQ&o=2874353341&rate=0
[libav/demuxer] flv: max_analyze_duration 5000000 reached
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
 (+) Subs  --sid=1 'tmp-danmaku2ass-hkjcs6xz.ass' (ass) (external)
[vo/opengl/x11] X11 error: GLXBadFBConfig
[vo/opengl] Could not create GL3 context. Retrying with legacy context.
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [pulse] 44100Hz stereo 2ch float
[libav] fps: No such option: round.
[libav] AVFilterGraph: Error initializing filter 'fps' with args 'fps=60:round=down'
[lavfi] Can't configure libavfilter graph.
Video filter chain:
 [vd] 512x384 yuv420p Autoselect/Autoselect CL=mpeg2/4/h264
 [in] 512x384 yuv420p BT.601 (SD)/TV CL=mpeg2/4/h264
 [lavfi] 512x384 yuv420p BT.601 (SD)/TV CL=mpeg2/4/h264   <---
 [out] ???
Cannot initialize video filters.
Could not initialize video chain.
Video: no video

**Comment by m13253** [comment]
这个问题的解决方法参考 #30
