### ISSUE TITLE
Can not get valid media URLs on New Animate

### ISSUE THREAD

**Issue by tonyrft** [m13253/BiliDan#37]
```
python3 ~/UsefulPythonScript/bilidan.py http://www.bilibili.com/video/av2331762/ --source overseas
INFO: Loading video info...
INFO: Got video cid: 3641122
INFO: Loading video content...
ERROR: Can not get valid media URLs.
```
I am not in China

**Comment by cthbleachbit** [comment]
Bilibili has copyright restrictions on those anime, so you might need a proxy server in mainland china.

**Comment by tonyrft** [comment]
Do I still have to use a proxy even I am using the --source overseas parameter? If so, what does that parameter do?

**Comment by cnbeining** [comment]
- Do I still have to use a proxy even I am using the --source overseas parameter?

Yes. "Overseas" source only means you are using "海外加速" API, also called "CDN" API. You have to deal with the IP restrictions by yourself.

One workaround is to use ```Proxifier``` to force Python to use your proxy.

Also you can check ```Biligrab```'s IP bypass function, which provides a simple function to bypass those restrictions. Please notice that it is never the goal of Biligrab to download copyright-restricted video.

**Comment by tonyrft** [comment]
I see, do you have any recommendations on Chinese proxy? And is it possible to add an porxy parameter in the program in the future? Thank you.

**Comment by cnbeining** [comment]
Personally I myself do not recommend any proxies. 

Technically speaking it is possible to add such function, but it depends of the plan of the author. @m13253

**Comment by cthbleachbit** [comment]
check `proxychains-ng` package. this package provides command-wide proxy handling.

**Comment by tonyrft** [comment]
Thank you very much.

From:  James Chai
Reply-To:  m13253/BiliDan
Date:  Friday, September 25, 2015 at 1:14 AM
To:  m13253/BiliDan
Cc:  Akatsuki Satou
Subject:  Re: [BiliDan] Can not get valid media URLs on New Animate (#37)


check proxychains-ng package. this package provides command-wide proxy handling.

**Comment by tonyrft** [comment]
Thank you very much.

**Comment by m13253** [comment]
BiliDan supports setting HTTP proxy via `http_proxy` and `https_proxy` environment variables.

For SOCKS protocol, use `proxychains_ng`.

Also you may try `flvcd` or `bilipr` as video source option.

**Comment by tonyrft** [comment]
The problem I am having is that I don’t have a chinese proxy(LOL)

**Comment by cnbeining** [comment]
Well, did you try reverse engineering ```Hola``` the Plugin?

**Comment by tonyrft** [comment]
Sorry, my programming skill aren’t very good.

**Comment by zanderzhng** [comment]
merge my commit and use -f. @tonyrft
