### ISSUE TITLE
Feature request: Freedesktop compliance

### ISSUE THREAD

**Issue by MingcongBai** [m13253/BiliDan#38]
Just as a thought that I mentioned to @m13253 over a instant messaging chat. I believe it is reasonable for BiliDan to consider a file type for a playlist/link-list, and with that type of file, BiliDan can use some Freedesktop technique to implement "double-click and play" support of certain Bilibili videos.

For example. A file like the following... (Shebang shows a distribution packaged scenario)

```
#!/usr/bin/bilidan 
http://www.bilibili.com/video/av2989364/
http://www.bilibili.com/video/av2995079/
```

As simple as a list of Bilibili links, or it can even be expanded with certain parameters (picture quality, play delay, etc. Which are already implemented by mpv itself). Then a .desktop file containing information and invoke details for BiliDan can be provided with the program itself, showing...

```
Exec=bilidan %U
```

And match it with a proper MIME type (even a new one to be introduced), then BiliDan can take care of reading these "list" files when double clicked in a file browser, with no need for command line operations.

Please, reply with questions and doubts.

**Comment by m13253** [comment]
Not many users need this feature. Closing now.
You are welcome to send me a pull request if you can implement it. ;-)
