### ISSUE TITLE
视频不从0秒开始播放

### ISSUE THREAD

**Issue by wygsephi** [m13253/BiliDan#41]
你好作者, 我今天才第一次接触这工具, 很是喜欢. 玩了一天还用Automator调了个applescript方便右键直接获取链接并调用, 感谢感谢.

我发现个问题, 启动mpv之后b站的视频都不是从0秒开始播放的, 都是从1%的地方开始, 这是怎么回事? 难道只有我是这种情况么..

**Comment by m13253** [comment]
是不是你启动的一瞬间按了键盘的方向键或者鼠标滚轮呢？
再看看 mpv 的初始配置文件（`~/.mpv`或`~/.config/mpv`）有什么内容？

**Comment by wygsephi** [comment]
为了确定我还特别在mpv.conf里加入了一行pause才发现打开的b站视频是1%开始的, 直接用mpv打开视频文件没有这个问题.

**Comment by m13253** [comment]
调用 bilidan 的时候加上 -d -v 两个参数，让其打印调试信息，然后把调试信息发上来让我分析一下吧。

Mac 的机器我现在没带在身边，所以调试起来可能有点不方便。
但是我是发现 Magic Mouse 的滚轮总是一不小心触发 mpv 的快进快退操作，所以我禁用了鼠标滚轮控制的控制。如果你也是用 Magic Mouse 或者 Magic Trackpad 可以看看是不是鼠标操作引起的快进。

**Comment by wygsephi** [comment]
经你一说可能是mpv的config文件里的问题我去验证了下, 发现是"hwdec=vda"这行出的问题, 虽然不知道是为什么, 删了就OK了..从别人那倒入的config给坑了...

感谢如此迅速的回复~

**Comment by m13253** [comment]
> 发现是"hwdec=vda"这行出的问题

诶？硬件加速导致的 bug？
诶……苹果的硬件加速啊……
不过 hwdec 还有几种模式可以选择，试试看别的模式有没有 bug 吧。
当然如果你不怕耗电也可以不用硬件加速（即使这样也比 Flash 省电）

**Comment by wygsephi** [comment]
尝试了下videotoolbox也并不行..
仔细看了下log差别在这里:
Using hardware decoding (videotoolbox).
Using conversion filter.
Image formats incompatible or invalid.
Video filter chain:
  [vd] 1280x720 videotoolbox auto/auto CL=mpeg2/4/h264
  [in] 1280x720 videotoolbox bt.709/limited CL=mpeg2/4/h264
  [scale] ??? [a]   <---
  [lavfi] ???
  [out] ???
Cannot initialize video filters.
Falling back to software decoding.

**Comment by m13253** [comment]
> 尝试了下videotoolbox也并不行..

给 bilidan 加上 --keep-fps 参数吧。但是会导致弹幕播放的帧率降到和视频本体一样。

**Comment by wygsephi** [comment]
完美解决, 3Q~
