### ISSUE TITLE
How to import the cookies with the command --cookie？

### ISSUE THREAD

**Issue by shuchang769** [m13253/BiliDan#43]
How can i log into my account automatically？

**Comment by cnbeining** [comment]
```
python bilidan.py --cookie "_octo=GH1.1.1911425777.1441768639; _gat=1; _ga=GA1.2.1205854411.1435622856; tz=America%2FNew_York" 
```

Something like that.

**Comment by ernestyao** [comment]
I'm using OS X + Safari. I found cookie information looks different from above example. How should I import cookies? I got something like _utma, tma, uTZ etc.

**Comment by cnbeining** [comment]
```
_utma, tma, uTZ
```

is normal. Just put it as what it likes.

**Comment by m13253** [comment]
> I'm using OS X + Safari. I found cookie information looks different from above example. How should I import cookies? I got something like _utma, tma, uTZ etc.

Open JavaScript console, type `document.cookie`.

**Comment by m13253** [comment]
I will close this, since it is solved.
