### ISSUE TITLE
Python version check code not run on Python 2

### ISSUE THREAD

**Issue by grenadn** [m13253/BiliDan#44]
Hello,

I noticed some code snippets like this:
```python
def biligrab(url, *, debug=False, verbose=False, …):
    pass
```
But the interpreter(python2 on OS X) shows syntax error(caused by asterisk)
and will also trigger 
```
File "bilidan.py", line 14
SyntaxError: Non-ASCII character '\xe2' in file bilidan.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

thus，
```python
if sys.version_info < (3, 0):
    sys.stderr.write('ERROR: Python 3.0 or newer version is required.\n')
    sys.exit(1)
```
will never run
Insignificant minor bug :-)

**Comment by cnbeining** [comment]
Unlike the original Biligrab, BiliDan is Python 3 only.

**Comment by grenadn** [comment]
haha, that code just a bit redundant 😄

**Comment by m13253** [comment]
> SyntaxError: Non-ASCII character '\xe2' in file bilidan.py on line 14, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

I fixed this by adding a charset declaration in e806ec11b61877e6aaf8e3dd6d15395e71fe2e7b.
But there is still an exception:
```python
  File "bilidan.py", line 61
    def biligrab(url, *, debug=False, verbose=False, media=None, cookie=None, quality=None, source=None, keep_fps=False, mpvflags=[], d2aflags={}, fakeip=None):
                       ^
SyntaxError: invalid syntax
```
I really don't know how to make the version check work. :joy:

**Comment by acgtyrant** [comment]
Add `#!/usr/bin/env python3` in the code, and point out the correct version is Python 3 in the main document and comments.

There is a another stupid solution: you write spilit the code into two parts: one for Python version check and the other for the main code. If the former find that the version is correct, execute the later, like `subprocess.run('main.py') while `main.py` has the correct shebang `#!/usr/bin/env python3`, or complain the user is using wrong Python.

**Comment by m13253** [comment]
Okay.
I already have the shebang.
Since there is no other way to solve it without introducing a seperate launcher, I will close it for now until I find a solution.
