### ISSUE TITLE
檀木加载不了

### ISSUE THREAD

**Issue by lowy** [m13253/BiliDan#45]
INFO: Loading video info...
INFO: Got video cid: 5409444
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-hbyc7-dx.acgvideo.com/vg126/a/c1/5409444-1.flv?expires=1450763700&ssig=qWggsXjNlan997Vyc1JQTQ&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 1280x720
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-l7m63fzj.ass
WARNING: Invalid comment: <d p="8.4219999313354,1,25,16777215,1450580975,0,328cbcda,1429304265"/>
INFO: Launching media player...
Playing: http://cn-hbyc7-dx.acgvideo.com/vg126/a/c1/5409444-1.flv?expires=1450763700&ssig=qWggsXjNlan997Vyc1JQTQ&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
Can not open external file /tmp/tmp-danmaku2ass-l7m63fzj.ass.
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:01:28 / 00:05:22 (27%) A-V:  0.000 Dropped: 4 Cache:  9s+42MB

Exiting... (Quit)

**Comment by m13253** [comment]
你好。请问你的平台是什么？Python版本呢？

正在播放途中的时候，看看 /tmp/tmp-danmaku2ass-????????.ass 这个字幕文件能不能打开？如果能，发上来开头几行内容。

**Comment by lowy** [comment]
arch32位系统 python默认的是3.5 字幕文件貌似正常 

[Script Info]
; Script generated by Danmaku2ASS
; https://github.com/m13253/danmaku2ass
Script Updated By: Danmaku2ASS (https://github.com/m13253/danmaku2ass)
ScriptType: v4.00+
PlayResX: 1920
PlayResY: 1080
Aspect Ratio: 1920:1080
Collisions: Normal
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.601

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Danmaku2ASS_0b6d, SimHei, 50, &H33FFFFFF, &H33FFFFFF, &H33000000, &H33000000, 0, 0, 0, 0, 100, 100, 0.00, 0.00, 1, 2, 0, 7, 0, 0, 0, 0

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 2,0:00:00.63,0:00:08.63,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 0, -200, 0)}我老婆！
Dialogue: 2,0:00:00.93,0:00:05.93,Danmaku2ASS_0b6d,,0000,0000,0000,,{\an8\pos(960, 0)\c&H793165&}看见我老婆进来了
Dialogue: 2,0:00:01.37,0:00:09.37,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 50, -150, 50)}见三滚
Dialogue: 2,0:00:01.40,0:00:09.40,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 100, -900, 100)}看见三三跟Bad Apple就进来了
Dialogue: 2,0:00:01.71,0:00:09.71,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 0, -150, 0)\c&H1300D3&}见三滚
Dialogue: 2,0:00:01.80,0:00:06.80,Danmaku2ASS_0b6d,,0000,0000,0000,,{\an8\pos(960, 50)\c&H1300D3&}我是冲封面来的
Dialogue: 2,0:00:01.80,0:00:06.80,Danmaku2ASS_0b6d,,0000,0000,0000,,{\an8\pos(960, 100)\c&H1300D3&}看见我三就进来了！
Dialogue: 2,0:00:02.81,0:00:10.81,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 0, -200, 0)}我是第一
Dialogue: 2,0:00:02.92,0:00:10.92,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 50, -350, 50)}╮(╯▽╰)╭
Dialogue: 2,0:00:02.93,0:00:10.93,Danmaku2ASS_0b6d,,0000,0000,0000,,{\move(1920, 150, -50, 150)}前

**Comment by m13253** [comment]
确实正常。。。
但是这一行

> Can not open external file /tmp/tmp-danmaku2ass-l7m63fzj.ass.

说明 mpv 没法打开这个字幕文件。


要么你给我AV号和启动的所有参数，以及MPV的配置文件（如果你有配置过的话），我看看能不能本地复现。

另外你升级一下系统（确认有没有 `-git` 结尾的包，可能需要手动升级），看看能不能解决问题。

总之我现在还没有找到解决方法，但是我可以帮助你一起解决问题。

**Comment by lowy** [comment]
系统每天都有更新 mpv也是默认的 
lowy@archer~ $ bilidan http://www.bilibili.com/video/av3426189/                                                                                                       [21:35:25]
INFO: Loading video info...
INFO: Got video cid: 5433600
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-scnc1-dx.acgvideo.com/vg2/4/5e/5433600-1.flv?expires=1450798500&ssig=nF4q4X-Sx3ROvYwTdDQvXA&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 1280x720
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-sn09btth.ass
INFO: Launching media player...
Playing: http://cn-scnc1-dx.acgvideo.com/vg2/4/5e/5433600-1.flv?expires=1450798500&ssig=nF4q4X-Sx3ROvYwTdDQvXA&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
Can not open external file /tmp/tmp-danmaku2ass-sn09btth.ass.
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
AV: 00:00:44 / 00:03:29 (21%) A-V:  0.000 Dropped: 12 Cache:  9s+8MB


Exiting... (Quit)

**Comment by m13253** [comment]
我试了一下是能出弹幕的。

是所有视频都不能加载弹幕还是只有这个视频？
另外加上 `--keep-fps` 这个参数能解决问题么？

![screenshot from 2015-12-22 21-47-17](https://cloud.githubusercontent.com/assets/1808930/11956498/9d2656ce-a8f5-11e5-8397-4e388aec5ea2.png)

**Comment by lowy** [comment]
近段时间都不行

**Comment by lowy** [comment]
搞定了 git clone 在本地播放正常 不明觉力
lowy@archer~/BiliDan git:(master) ✗$ python3 bilidan.py http://www.bilibili.com/video/av3426189/
INFO: Loading video info...
INFO: Got video cid: 5433600
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-scnc1-dx.acgvideo.com/vg2/4/5e/5433600-1.flv?expires=1450802100&ssig=NQL2-LWxRZtBvocStF9fhA&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 1280x720
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-cxzsvdt1.ass
INFO: Launching media player...
Playing: http://cn-scnc1-dx.acgvideo.com/vg2/4/5e/5433600-1.flv?expires=1450802100&ssig=NQL2-LWxRZtBvocStF9fhA&oi=3684215954&appkey=85eb6835b0a1034e&or=2002014922&rate=0
 (+) Video --vid=1 (h264)
 (+) Audio --aid=1 (aac)
 (+) Subs  --sid=1 'tmp-danmaku2ass-cxzsvdt1.ass' (ass) (external)
Opening video filter: [lavfi graph=fps=fps=60:round=down]
AO: [alsa] 48000Hz stereo 2ch float
VO: [opengl] 1280x720 yuv420p
fontselect: Using default font family: (SimHei, 400, 0) -> /usr/share/fonts/TTF/DejaVuSans.ttf, 0, (none)
fontselect: Using default font family: (SimHei, 400, 0) -> /usr/share/fonts/wenquanyi/wqy-zenhei/wqy-zenhei.ttc, 0, (none)

**Comment by m13253** [comment]
> 搞定了 git clone 在本地播放正常 不明觉力

啊。问题解决了就好。恭喜。

**Comment by wygsephi** [comment]
等等, 我刚更新了下mpv结果遇到了同样的问题, 求问怎么搞定的...

**Comment by cnbeining** [comment]
你确定danmaku2ass正常运行？

高级弹幕有可能无力 弹幕弹幕有可能吐啊。

**Comment by wygsephi** [comment]
没有正常运行, 显示的错误和上面一样, 更新完mpv突然出现的, 更新前一分钟还在用毫无异常.

Can not open external file /var/folders/t0/2s35033n1gq06fgvq_8y92pw0000gn/T/tmp-danmaku2ass-jfl1702b.ass.

**Comment by m13253** [comment]
> 没有正常运行, 显示的错误和上面一样, 更新完mpv突然出现的, 更新前一分钟还在用毫无异常.

如果你是 OS X 系统的话，是不是权限什么的出了问题？
先重启一下电脑看看？然后删除 danmaku2ass.py 文件让它重新下载看看？
你是用 Python 3 版本运行的么？

**Comment by m13253** [comment]
> 高级弹幕有可能无力

我用了半年时间研究高级弹幕……只要不是 JavaScript 那种，支持还是不错的。

**Comment by wygsephi** [comment]
删掉danmaku2ass.py然后重新载了竟然就自动解决了..前面出问题所以重新下了个bilidan覆盖, 看里面没有这个文件就没动原来是它的问题..

> 你是用 Python 3 版本运行的么？
我装了个python 3.4所以应该默认用的就是它吧

**Comment by wygsephi** [comment]
删掉danmaku2ass.py然后重新载了竟然就自动解决了..前面出问题所以重新下了个bilidan覆盖, 看里面没有这个文件就没动原来是它的问题..

> 你是用Python 3 版本运行的么？

我装了个python 3.4所以应该默认用的就是它吧

**Comment by m13253** [comment]
> 删掉danmaku2ass.py然后重新载了竟然就自动解决了..

恭喜！

**Comment by specter119** [comment]
@m13253 我也是同样的问题，同样解决了，是不是danmaku2ass.py不会自动更新？

**Comment by m13253** [comment]
> @m13253 我也是同样的问题，同样解决了，是不是danmaku2ass.py不会自动更新？

因为懒，所以没做自动更新。
所以为什么你一年没更新……

**Comment by cnbeining** [comment]
![image](https://cloud.githubusercontent.com/assets/1560962/18574246/4fb69166-7b99-11e6-8d55-7cd6cb83f0c1.png)
考虑到还有很多人用CentOS 5.。。。
