### ISSUE TITLE
Is it possible to add a '--no-merge-files' option?

### ISSUE THREAD

**Issue by guopm** [m13253/BiliDan#47]
Option --merge-files in mpv makes that all files in the playlist are concatenated into a single, big file. BiliDan enables it by default so that for users it looks like just a long video, with no split.
And that's what I'm embarrassed. I'm a college student and get a limited network bandwidth. That's to say, I am able to watch videos in bilibili.com IMMEDIATELLY only when I spend all my bandwidth. However, with --merge-files, mpv player always tries fetching videos parallelly, which means I have to wait for a long long time before it's ready. Then I remove that option in the script, and it just works like I watch the viedo in web browser.
So is it possible to add a '--no-merge-files' option? Although the strange duration would amaze users, I think time is more precious in a way.
Thanks!
A URL for test:`http://www.bilibili.com/video/av431146/`

**Comment by m13253** [comment]
Then the danmaku will not synchronize with the video,
unless you can manage to solve this problem.

I knew the parallel download problem, it is lucky that it only happens on old videos (pre 2014).
But I am sorry that I could not figure out a way to bypass this technical restriction.

If you have any idea, and know the way to implement it, feel free to tell me.
Anyway, you may try your plan in a separate fork, see if it works well, then merge back into the mainstream.

**Comment by m13253** [comment]
I knew a solution, the M3U with HLS extension trick.
But I could not get it working.

**Comment by guopm** [comment]
It will be the best if mpv provides sequential download natively...
Let me raise an issue and pray.

**Comment by cnbeining** [comment]
How about we just play individual videos while doing time-shift on danmaku file each time?

**Comment by m13253** [comment]
> How about we just play individual videos while doing time-shift on danmaku file each time?

I have once seen such an implementation [Bilibili-XBMC](https://github.com/Syndim/XBMC-Bilibili#已知问题).

I think we'd better wait for an answer from MPV's side (about whether to fix MPV).
After all, I can implement an extra layer of HTTP proxy to shape the extra download connections, possibly by force abort the first download attempt.

**Comment by Goshin** [comment]
I've met this problem few months ago, and I found controlling the buffer size would be helpful.

Just specify the `--cache`, `--cache-backbuffer`, `--cache-secs` options in the command line for Mpv. It will restrain the buffering of the not playing segments when limited buffer filled in.
Refer to https://github.com/Goshin/Yatto/blob/master/src/yatto.py#L136,L137
Official manual: https://mpv.io/manual/stable/

Note that the Mpv needs to fetch the video header of every segment to tell or estimate the playback duration, so the short wait in the beginning is necessary.

**Comment by m13253** [comment]
> I've met this problem few months ago, and I found controlling the buffer size would be helpful.

Thanks for your solution!
