### ISSUE TITLE
Mac 10.11.3 Error app has been blocked , can't get 'cid' from ...

### ISSUE THREAD

**Issue by specter119** [m13253/BiliDan#52]
python3 已经安装了

/bilidan.py http://www.bilibili.com/video/av899574/
INFO: Loading video info...
ERROR: Error message: app has been blocked.
ERROR: Can not get 'cid' from http://www.bilibili.com/video/av899574/

肿么破，前几天用fedora还是好好的

**Comment by cnbeining** [comment]
你用的是最新版？

**Comment by specter119** [comment]
> 
https://github.com/m13253/BiliDan/issues/52#issuecomment-195908359

是的啊，我刚刚换了mac没3天，我克隆下来的啊

**Comment by cnbeining** [comment]
最新的更新是2天前。。我无法复现。

**Comment by specter119** [comment]
好吧，我pull了一下，我再试试。

**Comment by specter119** [comment]
好了，谢谢😢😢

**Comment by cnbeining** [comment]
那就关了吧。。

**Comment by m13253** [comment]
Duplicate #50 , closing.
