### ISSUE TITLE
为什么会播放失败

### ISSUE THREAD

**Issue by LiarOnce** [m13253/BiliDan#57]
试了好多次，都是这个结果，怎么解决

liaronce@liaronce-desktop:~$ cd BiliDan
liaronce@liaronce-desktop:~/BiliDan$ ./bilidan.py http://www.bilibili.com/video/av4044639/
INFO: Loading video info...
INFO: Got video cid: 6525010
INFO: Loading video content...
INFO: Got media URLs:
      1: http://cn-gdfs16-dx.acgvideo.com/vg8/6/92/6525010-1.flv?expires=1462640400&ssig=V9HdLS-fCD7Kb_xmGY50eA&oi=463441933&appkey=452d3958f048c02a&or=244857364&rate=0
      2: http://cn-gdfs16-dx.acgvideo.com/vg8/6/92/6525010-2.flv?expires=1462640400&ssig=JcZAxZ42lo5HyxnHH_WTQw&oi=463441933&appkey=452d3958f048c02a&or=244857364&rate=0
      3: http://cn-gdfs16-dx.acgvideo.com/vg8/6/92/6525010-3.flv?expires=1462640400&ssig=TpVNfoOEjB0ufZVrrLupMQ&oi=463441933&appkey=452d3958f048c02a&or=244857364&rate=0
      4: http://cn-gdfs16-dx.acgvideo.com/vg8/6/92/6525010-4.flv?expires=1462640400&ssig=hT2ICjGZPMdWwNq05bBODw&oi=463441933&appkey=452d3958f048c02a&or=244857364&rate=0
      5: http://cn-gdfs16-dx.acgvideo.com/vg8/6/92/6525010-5.flv?expires=1462640400&ssig=_Am5f__uFUMOoZ7V66jkqA&oi=463441933&appkey=452d3958f048c02a&or=244857364&rate=0
INFO: Determining video resolution...
INFO: Video resolution: 1920x1080
INFO: Loading comments...
INFO: Invoking Danmaku2ASS, converting to /tmp/tmp-danmaku2ass-qv_xj3ry.ass
WARNING: Invalid comment: <d p="151.21299743652,5,25,14811775,1460738043,0,01d9eb99,1762232955"/>
WARNING: Invalid comment: <d p="10.340000152588,1,25,16777215,1461165266,0,ebfd449f,1776548331"/>
INFO: Launching media player...
Error parsing option force-media-title (option not found)
Setting command line option '--force-media-title=' failed.

Exiting... (Fatal error)

**Comment by m13253** [comment]
你需要更新 mpv 的版本，如果你用的是 Ubuntu 或者 Debian 那么很有可能你的默认 mpv 是几年前的版本。请自行更新到最新版再试。

**Comment by LiarOnce** [comment]
使用的确实是Ubuntu。。。。

**Comment by cnbeining** [comment]
任何Linux发行版都可以给你弄来祖爷爷辈的影音软件，以ffmpeg为甚，专门挤兑你不敢编译。

自己找个binary吧。
