### ISSUE TITLE
Application broken..

### ISSUE THREAD

**Issue by kexul** [m13253/BiliDan#58]
**output:**
```
INFO: Loading video info...
ERROR: Can not get 'cid' from http://www.bilibili.com/video/av4624739/
```

**Comment by cnbeining** [comment]
妈的最近所有appkey全死了。

我很愤怒。

腰疼还不想爬起来写代码。

要不然我们D他一拨泄泄愤吧。

2016年5月12日星期四，kexul <notifications@github.com> 写道：

**Comment by m13253** [comment]
B 站今天下午大规模更新，Flash 播放器在 Linux 下直接死机卡住整个页面。
同时 Bilibili 助手、BiliDan 全部失灵。
#FuckYouBishi
![screenshot_2016-05-12_22-55-38](https://cloud.githubusercontent.com/assets/1808930/15219208/72e1cc66-1828-11e6-9a51-bd40833559df.png)

**Comment by m13253** [comment]
> 要不然我们D他一拨泄泄愤吧。

可以，反正他们网页是 PHP 写的……
不过大部分都静态化了……而且还有自建 CDN，所以得找弱点。

**Comment by cnbeining** [comment]
我们不用很累很麻烦就可以对缓存投毒。

可惜这破站太小 不会造成蝴蝶效应。

2016年5月12日星期四，Star Brilliant <notifications@github.com> 写道：

**Comment by Lencerf** [comment]
[bilibili-mac-client](https://github.com/typcn/bilibili-mac-client) 依然能正常工作，能不能试图和那位开发者联系看看寻找解决方法？
![bilibili mac client](https://camo.githubusercontent.com/b219c3c657883ceb5eea9135cc743af301b4a0da/687474703a2f2f62696c696d61632e65716f652e636e2f696d616765732f706c617965725f6e65772e6a7067)

**Comment by cnbeining** [comment]
别。

他的key的来源方法还是不公开为好。

互相都留口饭吃。

**Comment by m13253** [comment]
我之前联系过他了，他通过仿真运行 Android 客户端的方式获得 key。

另外手机客户端上，用于签名的 key 和真正发送出去的 key 不相同，且前者会根据当前时间改变。逆向难度很大。

**Comment by cnbeining** [comment]
swf逆向我这没什么成果。。。

**Comment by m13253** [comment]
据说 flash 里有代码使用 C/C++ 写，用 flashcc 编译到 ABC。

**Comment by cnbeining** [comment]
FFDec就可以。

反编译后的代码很难读，完全看不出头绪。。

**Comment by m13253** [comment]
已修复。
