### ISSUE TITLE
Bilibili 新增了番剧字站，URL 格式发生改变

### ISSUE THREAD

**Issue by m13253** [m13253/BiliDan#63]
Bilibili 新增了番剧字站，URL 格式发生改变。

如 http://bangumi.bilibili.com/anime/v/85829

目前解决方法：

网页中，视频标题下方有 AV4305747 字样，是对应的旧站视频编号。

目前不打算更新 BiliDan，如果谁有需求可以自行开发然后申请 Pull Request。

**Comment by zaldnoay** [comment]
上解析器么= =

**Comment by CharlesOy** [comment]
引入bs4可以么？

**Comment by m13253** [comment]
> 写了一个新方法，不过引入了bs4，可以么？

现阶段 BiliDan 安装已经算是复杂了，我怕多一个依赖再搞挂一堆人。要么就简单地用正则匹配一下嘛？
以及做网络请求的话，用包装好的 `fetch_url` 函数吧，而不是直接用 `urllib`。因为它自带 User-Agent 伪造和 cookie 导入。

**Comment by CharlesOy** [comment]
确实加依赖不如之前方便。也没来得及看BiliDan的各个方法，新加的方法按照我自己习惯写的，我回头重新写过。

**Comment by m13253** [comment]
好哦。加油。👍

**Comment by kexul** [comment]
@CharlesOy 有个小问题不知道是否已经解决？_http://bangumi.bilibili.com/anime/v/34830_ 这个番有13集，然而每一集里面下面给的链接都是原来的旧站视频的第一集。
我看了一下目前的pull request里面的代码好像是没有解决这个问题的。。可能需要读取链接的目标网页，但是如何定位到具体的集数是个问题。。。

**Comment by CharlesOy** [comment]
@kexul 
我这段时间搞论文去了，要是有人想弄直接发PR吧然后at作者吧。
我刚粗略看了一下，我觉得在番组URL（例：http://bangumi.bilibili.com/anime/v/34830）中获取集数[Number]，然后在解析出来的一般URL中结尾加上index_[Number].html（例：http://www.bilibili.com/video/av379270/index_12.html）
没人发PR的话我下周末搞一下。话说狼与香辛料我还没补呢...

**Comment by kexul** [comment]
感谢～

**Comment by CharlesOy** [comment]
@m13253 已经把bs4包去掉了，解析正常。
另外@kexul 的问题也解决了，测了几个有分p的番剧集合的番组URL，目前的正则表达式解析没有问题，也许还有不兼容的番剧集合没测到，大家多测测。

**Comment by m13253** [comment]
已合并。
十分感谢你的贡献！
