### ISSUE TITLE
Bangumi Parse Issue

### ISSUE THREAD

**Issue by SilentAlice** [m13253/BiliDan#65]
Some archived bangumi can be parsed successfully. While serial bangumi which is not end yet has a parse error. 
**New bangumi is saved as an individual video. So we can not add index_n to preprocessed url naively.**

One alternative solution is to wait `response` in `fetch_video_metadata` to see if it is a *404 Not Found* and decide if we should remove the `index_n.html` from the url or set `pid` as 1 manually.

Also, I'm wondering if you can refer to http://www.flvcd.com to accelerate and simplify url parsing process. 
Thanks for your nice work!

**Comment by m13253** [comment]
Actually you can use `--source flvcd` to use flvcd parse service. But I am not sure if the code still works after its last update.

**Comment by m13253** [comment]
I will look into this issue next week after I reached home.

**Comment by SilentAlice** [comment]
flvcd works as long as the url is right.

**Comment by m13253** [comment]
Merged your code, closing.
Thank you for your support! ;-)
