### ISSUE TITLE
ERROR: Invalid URL: http://www.bilibili.com/av5697545/

### ISSUE THREAD

**Issue by WingGao** [m13253/BiliDan#68]
ERROR: Invalid URL: http://www.bilibili.com/av5697545/

具体链接出处：http://www.bilibili.com/ranking_beta

**Comment by m13253** [comment]
其实你楼了一个 video。

是：http://www.bilibili.com/video/av5697545/

不过 B 站在 Nginx 端好心帮你补上了（笑

**Comment by cnbeining** [comment]
Wait:

So you actually **typed** the URL into the shell?....

**Comment by m13253** [comment]
> So you actually typed the URL into the shell?....

B站那个链接也打错了，楼主用的那个链接。

**Comment by WingGao** [comment]
?????????????????????????????js????bilidan?????????????????bilidan?????url???????

? 2016?8?11????4:58?Star Brilliant <notifications@github.com<mailto:notifications@github.com>> ???


So you actually typed the URL into the shell?....

B???????????????????

-

**Comment by m13253** [comment]
看 `parse_url` 函数 76 行，代码如下
```python
        regex = re.compile('(http:/*[^/]+/video/)?av(\\d+)(/|/index.html|/index_(\\d+).html)?(\\?|#|$)')
```

是用一个正则把 av 号拉出来。你们看看这个正则怎么改比较好。

另外其实不要完整网址，只输入 `avXXXX` 或者 `avXXXX/index_Y.html` 也可以。

**Comment by WingGao** [comment]
```python
regex = re.compile('(.*?bilibili\.com.*?)?av(\\d+)(/|/index.html|/index_(\\d+).html)?(\\?|#|$)')
```
这样怎么样？

**Comment by m13253** [comment]
> 这样怎么样？

一个好的正则要能 block 掉所有不合法的格式，这样如果遇到了系统升级啊之类的改变，要能正确报错。
我改成了
```python
regex = re.compile('(?:http:/*[^/]+/(?:video/)?)?av(\\d+)(?:/|/index.html|/index_(\\d+).html)?(?:\\?|#|$)')
```
