### ISSUE TITLE
Can't use oversea source

### ISSUE THREAD

**Issue by tianren** [m13253/BiliDan#74]
Specifying the oversea source causes 'durl' error. 

> $./bilidan.py -s overseas http://www.bilibili.com/video/av5148011/
INFO: Loading video info...
INFO: Got video cid: 8365326
INFO: Loading video content...
ERROR: 'durl'

**Comment by m13253** [comment]
Bilibili has blocked many of our APPKEYs.
Try use `-s flvcd` as a temporary workaround.

**Comment by tianren** [comment]
If you still have private APPKEYs, we could setup a proxy server for api queries.  
I can provide two static IP.

**Comment by liushuyu** [comment]
Seems like `oversea` source no longer exists... at least in  Android client, the request URL is the same , and there is no difference if you turn the option `Overseas acceleration` on or off. But the URL does still exists.

**Comment by cnbeining** [comment]
Please check the latest algorithm at Biligrab.

2016年9月23日星期五，liushuyu <notifications@github.com> 写道：
