### ISSUE TITLE
is it possible that I play an local video from bilibili which i download via you-get

### ISSUE THREAD

**Issue by Trim21** [m13253/BiliDan#75]

**Comment by cnbeining** [comment]
Please consider ABPlayerHTML5-Py.

2016年9月2日星期五，Trim21 <notifications@github.com> 写道：

**Comment by m13253** [comment]
You can use [Danmaku2ASS](https://github.com/m13253/danmaku2ass), which is the core part of BiliDan.

Feed the `.cmt.xml` file you downloaded with you-get to Danmaku2ass, you will get an `.ass` subtitle file.
Play your video along with this file, and you will get danmaku.
