### ISSUE TITLE
mpv全屏后无法退出全屏

### ISSUE THREAD

**Issue by chy373** [m13253/BiliDan#76]
如题

**Comment by m13253** [comment]
请告诉我你的操作系统及版本，桌面环境及版本，MPV 版本。

已知 KDE 的 KWin_X11 会在一个应用进入全屏的时候随机崩溃，让你无法从全屏出来。这是 KDE 的 bug。临时解决方法是在 KWin_X11 崩溃的时候快捷键召唤 KRunner，输入 `kwin_x11 --replace` 重启 KWin_X11。

**Comment by m13253** [comment]
这是一个 MPV 的问题。请联系上游处理。我 close 啦。
