### ISSUE TITLE
"Error message: overspeed" when trying to acquire cid

### ISSUE THREAD

**Issue by dogtopus** [m13253/BiliDan#79]
I know that this project has been discontinued, but decided to post this issue anyway just for future reference.

It seems that similar issue also exists in Biligrab (cnbeining/Biligrab#30)

Log:

```
INFO: Loading video info...
ERROR: Error message: overspeed
ERROR: Can not get 'cid' from av314
Traceback (most recent call last):
  File "./bilidan.py", line 587, in <module>
    sys.exit(main())
  File "./bilidan.py", line 572, in main
    retval = retval or biligrab(url, debug=args.debug, verbose=args.verbose, media=args.media, comment=args.comment, cookie=args.cookie, quality=quality, source=source, keep_fps=args.keep_fps, mpvflags=mpvflags, d2aflags=d2aflags, fakeip=args.fakeip)
  File "./bilidan.py", line 302, in biligrab
    video_metadata = fetch_video_metadata(aid, pid)
  File "./bilidan.py", line 111, in fetch_video_metadata
    raise ValueError('Can not get \'cid\' from %s' % url)
ValueError: Can not get 'cid' from av314
```

**Comment by m13253** [comment]
Thank you for your report.
I will wait for Biligrab's response, because the parsing kernel is ported from that project.

**Comment by dogtopus** [comment]
Just tried it again and the problem no longer existed. Seems like an API quota issue.
Do Bilibili have API quotas like Youtube? I am not very familiar with Bilibili's API...

**Comment by cnbeining** [comment]
Yes in their documentation.

**Comment by dogtopus** [comment]
@cnbeining Too bad :(
I have a feeling that this problem will reappear again at any time.
API key authentication just don't work very well with open source projects :(

**Comment by cnbeining** [comment]
From the agreement I've met with them I am not supposed to release new API keys, so I do not bother to get a new one.

We could do a pool though.
