### ISSUE TITLE
ERROR: 'bytes' object has no attribute 'hex'

### ISSUE THREAD

**Issue by xhao79** [m13253/BiliDan#80]
./bilidan.py --source overseas http://www.bilibili.com/video/av7152135/
INFO: Loading video info...
INFO: Got video cid: 11666678
INFO: Loading video content...
WARNING: Bilibili API server indicates the API protocol has been updated, the extraction may not work!
ERROR: 'bytes' object has no attribute 'hex'

**Comment by m13253** [comment]
很显然，API 又被封了。
现在 B 站官方有 HTML 5 播放器之后我也没精力维护 BiliDan 了。

先凑合用 HTML 5 播放器吧，然后等大神破解。😂

**Comment by cnbeining** [comment]
SWF的抠出来了 看Biligrab。

**Comment by tcya** [comment]
把
`    fake_hw = random.Random().randrange(start=0, stop=18000000000000000084).to_bytes(8, 'big').hex()`
改成
`fake_hw = random.Random().randrange(start=0, stop=18000000000000000084).to_bytes(8, 'big')
    fake_hw = codecs.encode(fake_hw, 'hex_codec')`
就行了

**Comment by m13253** [comment]
感谢提供修复方法。
欢迎提交 pull request。
