### ISSUE TITLE
Please add support to support https.

### ISSUE THREAD

**Issue by persmule** [m13253/BiliDan#81]
Now bilibili and acgvideo support https access, please support them to provide better privacy.

**Comment by cnbeining** [comment]
It all depends on what the API gives us.

**Comment by persmule** [comment]
It seems now most APIs could be invoked via https.

**Comment by m13253** [comment]
This project is discontinued becaise I don't have enough time to maintain this. Sorry.

But I will appreciate if you could write this patch and send me a PR.

**Comment by persmule** [comment]
#82

**Comment by m13253** [comment]
Merged #82
